# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\14376\Desktop\DL\classification\utils\UI\UiPredict.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(744, 584)
        MainWindow.setMinimumSize(QtCore.QSize(744, 584))
        MainWindow.setMaximumSize(QtCore.QSize(744, 584))
        MainWindow.setStyleSheet("background:rgb(170, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.show = QtWidgets.QLabel(self.centralwidget)
        self.show.setGeometry(QtCore.QRect(20, 10, 461, 491))
        self.show.setStyleSheet("")
        self.show.setText("")
        self.show.setObjectName("show")
        self.outres = QtWidgets.QLineEdit(self.centralwidget)
        self.outres.setEnabled(False)
        self.outres.setGeometry(QtCore.QRect(600, 380, 101, 31))
        self.outres.setStyleSheet("background:rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 0);")
        self.outres.setText("")
        self.outres.setObjectName("outres")
        self.res_label = QtWidgets.QLabel(self.centralwidget)
        self.res_label.setGeometry(QtCore.QRect(500, 380, 91, 31))
        self.res_label.setStyleSheet("background:rgb(241, 206, 255);")
        self.res_label.setObjectName("res_label")
        self.openfile = QtWidgets.QPushButton(self.centralwidget)
        self.openfile.setGeometry(QtCore.QRect(500, 290, 201, 41))
        self.openfile.setStyleSheet("background:rgb(85, 255, 127);\n"
"font: 16pt \"Arial\";")
        self.openfile.setObjectName("openfile")
        self.detect = QtWidgets.QPushButton(self.centralwidget)
        self.detect.setGeometry(QtCore.QRect(500, 460, 201, 41))
        self.detect.setStyleSheet("background:rgb(85, 255, 127);\n"
"font: 16pt \"Arial\";")
        self.detect.setObjectName("detect")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(630, 10, 71, 41))
        self.exit.setStyleSheet("background-color: rgb(255, 0, 127);\n"
"font: 16pt \"Arial\";")
        self.exit.setObjectName("exit")
        self.cfginfer = QtWidgets.QPushButton(self.centralwidget)
        self.cfginfer.setGeometry(QtCore.QRect(500, 200, 201, 41))
        self.cfginfer.setStyleSheet("background:rgb(85, 255, 127);\n"
"font: 16pt \"Arial\";")
        self.cfginfer.setObjectName("cfginfer")
        self.checkBox_model = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_model.setEnabled(False)
        self.checkBox_model.setGeometry(QtCore.QRect(500, 50, 121, 19))
        self.checkBox_model.setStyleSheet("color: rgb(0, 0, 0);")
        self.checkBox_model.setCheckable(True)
        self.checkBox_model.setObjectName("checkBox_model")
        self.checkBox_pic = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_pic.setEnabled(False)
        self.checkBox_pic.setGeometry(QtCore.QRect(500, 80, 121, 19))
        self.checkBox_pic.setStyleSheet("color: rgb(0, 0, 0);")
        self.checkBox_pic.setCheckable(True)
        self.checkBox_pic.setObjectName("checkBox_pic")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 744, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.res_label.setText(_translate("MainWindow", "识别结果为："))
        self.openfile.setText(_translate("MainWindow", "加载图片"))
        self.detect.setText(_translate("MainWindow", "识别"))
        self.exit.setText(_translate("MainWindow", "退出"))
        self.cfginfer.setText(_translate("MainWindow", "推理配置"))
        self.checkBox_model.setText(_translate("MainWindow", "模型已配置"))
        self.checkBox_pic.setText(_translate("MainWindow", "图片已加载"))
