# config info
model_name : "AlexNet"
logs_save_path : "logs"


# config hyper-parameters
input_size : 224                      # images input size
class_num : 2                         # output size (class numbers)
EPOCH : 100                           # epoch nums
batch_size : 16                       # batch size numbers
batch_size_val: 4                     # val batch size numbers
lr : 0.01                             # init learing rate
EarlyStop : True                      # Whether to adopt early stop strategy
EarlyStopEpoch : 15                   # Stop training if accuracy has not improved after 15 epochs
